nitpick: buggy (inverted) message in intention of main entry file

diff --git a/yabashlib b/yabashlib
--- a/yabashlib
+++ b/yabashlib
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 
 if [[ "${BASH_SOURCE[0]}" = "$0" ]];then
-  printf 'Error: `yabashlib` wrapper intended as a script, not a source!\n' >&2
+  printf 'Error: `yabashlib` wrapper intended as a source, not an invokable script!\n' >&2
   exit 1
 fi
 
